version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_create_environment:
      - conda activate sm_dev
      - mkdir build
      - cd build
      - cmake .. -DSPHINX_HTML_DIR=$READTHEDOCS_OUTPUT/html/ # can also put sth to $READTHEDOCS_OUTPUT/pdf/
      - make docs 

conda:
  environment: docs_conf/dev_env_linux.yml