version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"
  commands:
    - conda env create -f docs_conf/dev_env_linux.yml
    - conda init bash
    - mkdir build
    - cd build
    - bash -c "conda activate sm_dev; cmake .. -DSPHINX_HTML_DIR=$READTHEDOCS_OUTPUT/html/; make docs"
    # can also put sth to $READTHEDOCS_OUTPUT/pdf/
