version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_checkout:
      - git submodule update --init --recursive
    post_create_environment:
      - mkdir build
      - cmake . -B build -DSPHINX_HTML_DIR=$READTHEDOCS_OUTPUT/html/
      - cmake --build build --target docs
      - mkdir $READTHEDOCS_OUTPUT/pdf/
      - tectonic build/tex/*.tex -o $READTHEDOCS_OUTPUT/pdf/

conda:
  environment: docs_conf/dev_env_linux.yml