version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  commands:
    - conda env create -f docs_conf/dev_env_linux.yml
    - conda activate sm_dev
    - mkdir build
    - cd build
    - cmake .. -DSPHINX_HTML_DIR=$READTHEDOCS_OUTPUT/html/
    - make docs 
