{% set version = "0.2.0" %}
#{% set sha256 = "69e1f48063cd948ff2eb35c4998701a05e52f6bdf15c84a1141931c086875014" %}

package:
  name: libsps
  version: '{{version}}'

source:
  path: ".."
  #sha256: "{{sha256}}"
  #url: "https://github.com/MarkusRainerSchmidt/libSmoother/archive/{{version}}.tar.gz"

build:
  number: 0
  skip: true # [py2k or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python>=3.6
    - pybind11>=2.8.0
  run:
    - python>=3.6

test:
  imports:
    - sps

about:
  home: https://github.com/MarkusRainerSchmidt/libSps
  license: MIT
  summary: O(1) region count queries using sparse prefix sums