# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
    - name: Install dependencies
      run: |
        /opt/python/cp39-cp39/bin/python -m pip install --upgrade pip
        /opt/python/cp39-cp39/bin/python -m pip install wheel==0.40.0 pybind11==2.8.0 gcc==9.4.0 gx==9.4.0
    - name: Build package
      run: |
        /opt/python/cp39-cp39/bin/python setup.py bdist_wheel
      env:
       CC:   gcc-9
       CXX:  g++-9
    - name: Audit wheel
      run: |
        /opt/python/cp39-cp39/bin/python -m pip install auditwheel==5.4.0 patchelf==0.17.2
        auditwheel show dist/*.whl
        auditwheel repair --strip --plat manylinux2014_x86_64 --exclude libgomp.so.1 dist/*.whl
        rm -r dist
        mv wheelhouse dist
