# pip install --index-url https://test.pypi.org/simple/ your-package

name: Test Import

on:
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ${{ matrix.os }}
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
          os: ["ubuntu-latest", "windows-latest", "mac-latest"]
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: pip install --index-url https://test.pypi.org/simple/ libSps
    - name: Import package
      run: python -c "import sps; print(sps.VERSION)"