# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    strategy:
      fail-fast: false
      matrix:
          python-version: ["cp39-cp39"]

    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: |
        git config --global --add safe.directory '*'
        git submodule update --init --recursive
    - name: Install dependencies
      run: |
        /opt/python/${{ matrix.python-version }}/bin/python -m pip install --upgrade pip
        /opt/python/${{ matrix.python-version }}/bin/python -m pip install wheel==0.40.0 pybind11==2.8.0 auditwheel==5.4.0
    - name: Build package
      run: |
        /opt/python/${{ matrix.python-version }}/bin/python setup.py bdist_wheel -vvv
    - name: Audit wheel
      run: |
        /opt/python/${{ matrix.python-version }}/bin/python -m auditwheel repair --strip --plat manylinux2014_x86_64 --exclude libgomp.so.1 dist/*.whl
        rm -r dist
        mv wheelhouse dist
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist

  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.40.0 pybind11==2.8.0
    - name: Build package
      run: python setup.py bdist_wheel
      env:
       CC:   gcc-9
       CXX:  g++-9
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist

  build-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
          python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel==0.40.0 pybind11==2.8.0
    - name: Build package
      run: python setup.py bdist_wheel
      env:
       CC:   gcc-9
       CXX:  g++-9
    - uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist
